version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/node:14.16.0-browsers

jobs:
  buildAndDeploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - checkout
      - run:
          name: Install Dependencies
          command: npm i
      - run:
          name: Build
          command: npm run build
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish --access=public

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - buildAndDeploy